[workspace]
members = [
  "mdbook-exerciser",
  "src/exercises",
  "src/bare-metal/useful-crates/allocator-example",
  "src/bare-metal/useful-crates/zerocopy-example",
  "src/exercises/concurrency/chat-async",
  "src/rust-wasm-template/project",
  "src/rust-wasm-template/server",
]
